export default {
  login: "RIBTAS007",
  id: 26746941,
  node_id: "MDQ6VXNlcjI2NzQ2OTQx",
  avatar_url: "https://avatars.githubusercontent.com/u/26746941?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/RIBTAS007",
  html_url: "https://github.com/RIBTAS007",
  followers_url: "https://api.github.com/users/RIBTAS007/followers",
  following_url:
    "https://api.github.com/users/RIBTAS007/following{/other_user}",
  gists_url: "https://api.github.com/users/RIBTAS007/gists{/gist_id}",
  starred_url: "https://api.github.com/users/RIBTAS007/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/RIBTAS007/subscriptions",
  organizations_url: "https://api.github.com/users/RIBTAS007/orgs",
  repos_url: "https://api.github.com/users/RIBTAS007/repos",
  events_url: "https://api.github.com/users/RIBTAS007/events{/privacy}",
  received_events_url: "https://api.github.com/users/RIBTAS007/received_events",
  type: "User",
  site_admin: false,
  name: "SATBIR SINGH",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "I LIKE TO DO CODING. I AM A BEGINNER IN THIS FIELD.",
  twitter_username: null,
  public_repos: 43,
  public_gists: 0,
  followers: 4,
  following: 4,
  created_at: "2017-03-28T17:05:40Z",
  updated_at: "2024-02-14T20:33:36Z",
};
